//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocalDatabase
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestTable
    {
        public System.Guid GuidId { get; set; }
        public string VarcharType { get; set; }
        public Nullable<System.DateTimeOffset> OffsetTypeDate { get; set; }
        public Nullable<System.DateTime> DateTimeType { get; set; }
        public Nullable<System.DateTime> OnlyDate { get; set; }
        public Nullable<bool> BooleanType { get; set; }
    }
}
